project:
  type: website
  output-dir: docs

website:
  title: "Jalen Miller's Website Warmup"
  site-path: "/personal-jalen-miller/"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: articles/index.qmd
        text: Artcles

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      logo: "images/articleee.jpeg"
      collapse-level: 2
      contents: 
        - text: "Reversing an Array"
          href:  articles/RevArr/index.qmd
        - text: "Groups"
          href:  articles/Groups/index.qmd


format:
  html:
    theme: dark
    css: styles.css
    toc: true









